from repos.assigment import *
from repos.bytes import *
from repos.classes import *
from repos.collections_1 import *
from repos.decorators_1 import *
from repos.dict_1 import *
from repos.dataclasses import *
from repos.dunder_1 import *
from repos.list_comps_1 import *
from repos.list_1 import *
from repos.pattern_matching_1 import *
from repos.repo_1 import *
from repos.set_1 import *
from repos.slicing_1 import *
from repos.protocols import *
from repos.unpacking_1 import *
from repos.operator_overloading import *
from repos.references import *
from repos.first_class_functions import *